
# parsetab.py
# This file is automatically generated. Do not edit.
_tabversion = '3.8'

_lr_method = 'LALR'

_lr_signature = 'CD80101E944BB5AD4CACD224D8252596'
    
_lr_action_items = {'LBRACE':([13,],[17,]),'ICONST':([6,17,30,31,33,34,46,47,48,],[7,26,36,37,26,39,51,53,54,]),'SCONST':([1,4,],[3,5,]),'FCONST':([46,],[52,]),'RPAREN':([18,51,52,53,],[27,55,56,57,]),'IMPROVISATION':([7,],[9,]),'KCONST':([14,],[18,]),'STRUCTURE':([8,11,19,23,28,43,44,45,50,58,],[13,13,-5,-3,-4,-13,-11,-6,-12,-14,]),'DCONST':([35,41,42,43,58,],[42,42,-17,42,-14,]),'AUTHOR':([3,],[4,]),'SONG':([7,],[10,]),'RBRACE':([24,25,38,57,],[32,-20,-19,-21,]),'COLON':([10,27,],[15,35,]),'LBRACKET':([20,21,29,40,41,42,49,55,56,],[-8,30,-7,48,-16,-17,-15,-9,-10,]),'INSTRUMENT':([5,],[6,]),'LPAREN':([9,22,26,],[14,31,34,]),'COMMA':([25,37,39,57,],[33,46,47,-21,]),'NCONST':([15,19,20,45,55,56,],[22,22,22,-6,-9,-10,]),'FILENAME':([0,],[1,]),'$end':([2,12,16,32,],[0,-2,-1,-18,]),'RBRACKET':([36,54,],[45,58,]),}

_lr_action = {}
for _k, _v in _lr_action_items.items():
   for _x,_y in zip(_v[0],_v[1]):
      if not _x in _lr_action:  _lr_action[_x] = {}
      _lr_action[_x][_k] = _y
del _lr_action_items

_lr_goto_items = {'degree':([35,41,43,],[41,49,41,]),'notes':([15,19,20,],[21,21,29,]),'structure':([8,11,],[12,16,]),'degrees':([35,43,],[40,40,]),'notesLine':([15,19,],[19,19,]),'improv':([7,],[8,]),'note':([15,19,20,],[20,20,20,]),'song':([7,],[11,]),'repeat':([17,33,],[24,38,]),'principal':([0,],[2,]),'notesLines':([15,19,],[23,28,]),'degreeLines':([35,43,],[44,50,]),'repeatValues':([17,33,],[25,25,]),'degreeLine':([35,43,],[43,43,]),}

_lr_goto = {}
for _k, _v in _lr_goto_items.items():
   for _x, _y in zip(_v[0], _v[1]):
       if not _x in _lr_goto: _lr_goto[_x] = {}
       _lr_goto[_x][_k] = _y
del _lr_goto_items
_lr_productions = [
  ("S' -> principal","S'",1,None,None,None),
  ('principal -> FILENAME SCONST AUTHOR SCONST INSTRUMENT ICONST song structure','principal',8,'p_principal','AnalizadorSintactico.py',37),
  ('principal -> FILENAME SCONST AUTHOR SCONST INSTRUMENT ICONST improv structure','principal',8,'p_principal2','AnalizadorSintactico.py',46),
  ('song -> SONG COLON notesLines','song',3,'p_song','AnalizadorSintactico.py',56),
  ('notesLines -> notesLine notesLines','notesLines',2,'p_notesLines','AnalizadorSintactico.py',62),
  ('notesLines -> notesLine','notesLines',1,'p_notesLines2','AnalizadorSintactico.py',66),
  ('notesLine -> notes LBRACKET ICONST RBRACKET','notesLine',4,'p_notesLine','AnalizadorSintactico.py',71),
  ('notes -> note notes','notes',2,'p_notes','AnalizadorSintactico.py',78),
  ('notes -> note','notes',1,'p_notes2','AnalizadorSintactico.py',82),
  ('note -> NCONST LPAREN ICONST COMMA ICONST RPAREN','note',6,'p_note','AnalizadorSintactico.py',87),
  ('note -> NCONST LPAREN ICONST COMMA FCONST RPAREN','note',6,'p_note2','AnalizadorSintactico.py',102),
  ('improv -> IMPROVISATION LPAREN KCONST RPAREN COLON degreeLines','improv',6,'p_improv','AnalizadorSintactico.py',118),
  ('degreeLines -> degreeLine degreeLines','degreeLines',2,'p_degreeLines','AnalizadorSintactico.py',135),
  ('degreeLines -> degreeLine','degreeLines',1,'p_degreeLines2','AnalizadorSintactico.py',139),
  ('degreeLine -> degrees LBRACKET ICONST RBRACKET','degreeLine',4,'p_degreeLine','AnalizadorSintactico.py',144),
  ('degrees -> degree degree','degrees',2,'p_degrees','AnalizadorSintactico.py',150),
  ('degrees -> degree','degrees',1,'p_degrees2','AnalizadorSintactico.py',154),
  ('degree -> DCONST','degree',1,'p_degree','AnalizadorSintactico.py',159),
  ('structure -> STRUCTURE LBRACE repeat RBRACE','structure',4,'p_structure','AnalizadorSintactico.py',165),
  ('repeat -> repeatValues COMMA repeat','repeat',3,'p_repeat','AnalizadorSintactico.py',170),
  ('repeat -> repeatValues','repeat',1,'p_repeat2','AnalizadorSintactico.py',174),
  ('repeatValues -> ICONST LPAREN ICONST COMMA ICONST RPAREN','repeatValues',6,'p_repeatValues','AnalizadorSintactico.py',179),
]
